# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170310_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='centro',
            field=models.TextField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.TextField(default='', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='responsable',
            field=models.TextField(default='', max_length=100, null=True),
        ),
    ]
