# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='surname',
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.TextField(blank='True', default='', max_length=30),
        ),
    ]
