# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20170311_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_name',
            field=models.CharField(blank='True', default='', max_length=150),
        ),
    ]
